#!/usr/bin/env node
/**
 * @file utils/generate-vendors.js
 * @description Regenerate the vendored third-party bundles in `vendor/`.
 *
 *   Vendored files follow the noflo-ui convention: committed prebuilt
 *   bundles at the package root `vendor/` directory, with the name and
 *   pinned version in the filename. They carry no runtime registry
 *   dependency — the whole point is durability against upstream
 *   disappearance (see the in-process fbp-spec runner work document and
 *   the SPEC's minimize-dependencies principle).
 *
 *   - `jsonpath-plus-<v>.js`: the package's own single-file browser ESM
 *     distribution, copied verbatim (self-contained, no imports).
 *   - `yaml-<v>.js`: the `yaml` package has no single-file distribution,
 *     so its browser entry is bundled to one ESM file with esbuild
 *     (fetched on demand via npx; only needed when regenerating).
 *
 *   Each bundle gets a `// @ts-nocheck` pragma prepended so the
 *   package's type checking skips vendored code.
 *
 *   Run from the package root:  node utils/generate-vendors.js
 *   Requires network access (npm registry). Commit the results together
 *   with the matching LICENSE-* files.
 */

import { execSync } from "node:child_process";
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PKG_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** @type {{ name: string, version: string }[]} */
const VENDORED = [
  { name: "jsonpath-plus", version: "11.1.0" },
  { name: "yaml", version: "2.9.1" },
];

/** Prepend the no-type-check pragma so tsc skips the bundle. */
const withNocheck = (source) =>
  `// @ts-nocheck — vendored bundle, not type-checked\n${source}`;

/**
 * Rewrite JSDoc `@import` specifiers that reference the package's own
 * upstream entry file (for example `./jsonpath.js`) so they point at
 * the vendored filename instead — the vendored file is renamed, and
 * Deno's checker resolves `@import` specifiers statically.
 *
 * @param {string} source
 * @param {string} upstreamEntry
 * @param {string} vendoredName
 * @returns {string}
 */
const withSelfImports = (source, upstreamEntry, vendoredName) =>
  source.split(upstreamEntry).join(vendoredName);

const tmp = mkdtempSync(join(tmpdir(), "fbp-spec-runner-vendor-"));
try {
  mkdirSync(join(PKG_ROOT, "vendor"), { recursive: true });

  // Install the pinned versions locally so everything resolves exactly them
  const deps = VENDORED.map((pkg) => `${pkg.name}@${pkg.version}`).join(" ");
  execSync(`npm install ${deps} --silent --no-save`, { cwd: tmp });

  for (const pkg of VENDORED) {
    execSync(`npm pack ${pkg.name}@${pkg.version} --silent`, { cwd: tmp });
    const extract = join(tmp, `${pkg.name}-pkg`);
    mkdirSync(extract, { recursive: true });
    execSync(`tar xzf ${pkg.name}-${pkg.version}.tgz -C ${extract}`, {
      cwd: tmp,
    });
    const from = join(extract, "package");
    const target = join(PKG_ROOT, "vendor", `${pkg.name}-${pkg.version}.js`);

    if (pkg.name === "jsonpath-plus") {
      writeFileSync(
        target,
        withSelfImports(
          withNocheck(
            readFileSync(join(from, "dist/index-browser-esm.js"), "utf8"),
          ),
          "./jsonpath.js",
          `${pkg.name}-${pkg.version}.js`,
        ),
      );
    } else {
      execSync(
        `npx -y esbuild node_modules/${pkg.name}/browser/index.js ` +
          `--bundle --format=esm --platform=browser ` +
          `--outfile=${target}`,
        { cwd: tmp },
      );
      writeFileSync(target, withNocheck(readFileSync(target, "utf8")));
    }
    cpSync(
      join(from, "LICENSE"),
      join(PKG_ROOT, "vendor", `LICENSE-${pkg.name}`),
    );
    console.log(`vendored ${pkg.name}@${pkg.version}`);
  }

  writeFileSync(
    join(PKG_ROOT, "vendor", "README.md"),
    `# Vendored bundles\n\n` +
      VENDORED.map(
        (p) =>
          `- \`${p.name}-${p.version}.js\` — ${p.name}@${p.version} (see LICENSE-${p.name})\n`,
      ).join("") +
      `\nGenerated by \`node utils/generate-vendors.js\` (needs network). Each file carries a @ts-nocheck pragma and is excluded from linting.\n`,
  );
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
