name: Run tests

on: [push, pull_request]

jobs:
  node:
    name: Test with Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check file formatting against EditorConfig
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm test
